import { useNavigate } from 'react-router-dom';
import './LegalPage.css';

export default function PrivacyPolicy() {
  const navigate = useNavigate();
  return (
    <div className="legal-page">
      <div className="legal-page__inner">
        <button className="legal-page__back" onClick={() => navigate(-1)}>← Back</button>
        <h1 className="legal-page__title">Privacy Policy</h1>
        <p className="legal-page__date">Last updated: April 2025</p>

        <section className="legal-page__section">
          <h2>1. Overview</h2>
          <p>CINIMATE ("we", "the Service") is committed to protecting your privacy. This Privacy Policy explains what information we collect, how we use it, and the choices you have regarding your data. By using the Service, you agree to the collection and use of information as described in this policy.</p>
        </section>

        <section className="legal-page__section">
          <h2>2. Information We Collect</h2>
          <p>We collect information in two ways:</p>
          <ul>
            <li><strong>Information you provide:</strong> When you create an account, we collect your email address and a hashed version of your password. We do not store your password in plain text.</li>
            <li><strong>Information generated by your use:</strong> Your watchlist, ratings, "not interested" selections, liked actors, and TV series progress are stored to power personalised recommendations and cloud sync.</li>
            <li><strong>Guest mode:</strong> If you use the Service without an account, all data is stored locally on your device only and is never transmitted to our servers.</li>
          </ul>
        </section>

        <section className="legal-page__section">
          <h2>3. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide, maintain, and improve the Service</li>
            <li>Generate personalised film and TV recommendations</li>
            <li>Sync your data across multiple devices when you are signed in</li>
            <li>Maintain your watchlist, ratings, and progress across sessions</li>
          </ul>
          <p>We do not use your personal information for advertising, and we do not sell your data to third parties.</p>
        </section>

        <section className="legal-page__section">
          <h2>4. Data Storage and Security</h2>
          <p>Account data and user-generated content (watchlists, ratings, etc.) are stored securely using Supabase, a third-party cloud database provider. Data is encrypted in transit using HTTPS. We implement reasonable technical measures to protect your information, but no system is completely secure.</p>
        </section>

        <section className="legal-page__section">
          <h2>5. Third-Party Services</h2>
          <p>The Service uses the following third-party services:</p>
          <ul>
            <li><strong>The Movie Database (TMDB):</strong> Provides all film and TV metadata, posters, and cast information. Queries to TMDB may include general request metadata but do not include your personal account information.</li>
            <li><strong>Supabase:</strong> Provides database and authentication infrastructure for registered users.</li>
            <li><strong>Vercel:</strong> Hosts the application front end.</li>
          </ul>
          <p>Each of these services has its own privacy policy. We are not responsible for the privacy practices of these third parties.</p>
        </section>

        <section className="legal-page__section">
          <h2>6. Cookies and Local Storage</h2>
          <p>The Service uses browser localStorage to store preferences such as your selected language, theme, and — in guest mode — your watchlist and ratings. Authentication tokens for signed-in users are stored in browser session storage managed by Supabase. We do not use tracking cookies or third-party advertising cookies.</p>
        </section>

        <section className="legal-page__section">
          <h2>7. Your Rights</h2>
          <p>You have the right to:</p>
          <ul>
            <li>Access the personal data we hold about you</li>
            <li>Request deletion of your account and associated data via the Profile settings</li>
            <li>Use the Service in guest mode without providing any personal information</li>
            <li>Export or clear your locally stored data at any time by clearing browser storage</li>
          </ul>
        </section>

        <section className="legal-page__section">
          <h2>8. Children's Privacy</h2>
          <p>The Service is not directed at children under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us so we can take appropriate action.</p>
        </section>

        <section className="legal-page__section">
          <h2>9. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify users of material changes where reasonably practicable. Continued use of the Service after changes are posted constitutes acceptance of the revised policy.</p>
        </section>

        <section className="legal-page__section">
          <h2>10. Contact</h2>
          <p>If you have any questions about this Privacy Policy or how your data is handled, please reach out via the About page of the application.</p>
        </section>
      </div>
    </div>
  );
}